[package]
name = "gosling-fuzz"
version = "0.0.0"
rust-version = "1.63"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
bson = ">= 2.0, <= 2.4.0"
data-encoding = "^2"
honk-rpc = { path = "../../honk-rpc" }
libfuzzer-sys = { version = "^0.4", features = ["arbitrary-derive"] }
tor-interface = { path = "../../tor-interface" }

[dependencies.gosling]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_identity_server"
path = "fuzz_targets/fuzz_identity_server.rs"
test = false
doc = false

[[bin]]
name = "fuzz_identity_client"
path = "fuzz_targets/fuzz_identity_client.rs"
test = false
doc = false

[[bin]]
name = "fuzz_endpoint_server"
path = "fuzz_targets/fuzz_endpoint_server.rs"
test = false
doc = false

[[bin]]
name = "fuzz_endpoint_client"
path = "fuzz_targets/fuzz_endpoint_client.rs"
test = false
doc = false