[package]
name = "tor-interface"
authors = ["morgan <morgan@torproject.org>", "Richard Pospesel <richard@blueprintforfreespeech.net>"]
version = "0.5.0"
rust-version = "1.70"
edition = "2021"
license = "BSD-3-Clause"
description = "A library providing a Rust interface to interact with the legacy tor daemon"
keywords = ["tor", "anonymity"]
repository = "https://github.com/blueprint-freespeech/gosling"

[dependencies]
arti-client = { version = "0.31.0", features = ["ephemeral-keystore", "experimental-api", "keymgr", "onion-service-client", "onion-service-service", "tokio"], optional = true}
arti-rpc-client-core = { version = "0.31.0", optional = true }
curve25519-dalek = "4.1"
data-encoding = "2.0"
data-encoding-macro = "0.1"
domain = "<= 0.10.0"
idna = "1"
rand = "0.9"
rand_core = "0.9"
regex = "1.9"
sha1 = "0.10"
sha3 = "0.10"
signature = "1.5"
socks = "0.3"
static_assertions = "1.1"
thiserror = "1.0"
tokio = { version = "1", features = ["macros"], optional = true }
tokio-stream = { version = "0", optional = true }
tor-cell = { version = "0.31.0", optional = true }
tor-config = { version = "0.31.0", optional = true }
tor-hsservice = { version = "0.31.0", optional = true, features = ["restricted-discovery"] }
tor-keymgr = { version = "0.31.0", optional = true, features = ["keymgr"] }
tor-llcrypto = { version = "0.31.0", features = ["relay"] }
tor-proto = { version = "0.31.0", features = ["stream-ctrl"], optional = true }
tor-rtcompat = { version = "0.31.0", optional = true }
hmac = { version = "0.12", optional = true }
sha2 = { version = "0.10", optional = true }

[dev-dependencies]
anyhow = "1.0"
serial_test = "0.9"
which = "4.4"

[features]
arti-client-tor-provider = ["arti-client", "tokio", "tokio-stream", "tor-cell", "tor-config", "tor-hsservice", "tor-keymgr", "tor-proto", "tor-rtcompat"]
arti-tor-provider = ["arti-rpc-client-core"]
mock-tor-provider = []
legacy-tor-provider = ["hmac", "sha2"]
