[package]
name = "tor-interface"
authors = ["Richard Pospesel <richard@blueprintforfreespeech.net>"]
version = "0.2.1"
rust-version = "1.70"
edition = "2021"
license = "BSD-3-Clause"
description = "A library providing a Rust interface to interact with the legacy tor daemon"
keywords = ["tor", "anonymity"]
repository = "https://github.com/blueprint-freespeech/gosling"

[dependencies]
curve25519-dalek = "4.1"
data-encoding = "2.0"
data-encoding-macro = "0.1"
rand = "0.8"
rand_core = "0.6"
regex = "1.9"
sha1 = "0.10"
sha3 = "0.10"
signature = "1.5"
socks = "0.3"
static_assertions = "1.1"
thiserror = "1.0"
tor-llcrypto = { version = "0.7", features = ["relay"] }

[dev-dependencies]
anyhow = "1.0"
serial_test = "0.9"
which = "4.4"

[features]
offline-test = []
