[package]
name = "tor-interface"
authors = ["Richard Pospesel <richard@blueprintforfreespeech.net>"]
version = "0.1.0"
rust-version = "1.66"
edition = "2021"
license = "BSD-3-Clause"
description = "A library providing a Rust interface to interact with the legacy tor daemon"
keywords = ["tor", "anonymity"]
repository = "https://github.com/blueprint-freespeech/gosling"

[dependencies]
data-encoding = "2.3.2"
data-encoding-macro = "0.1.12"
rand = "0.8.5"
rand_core = "0.6.3"
regex = "1.5.5"
rust-crypto = "^0.2"
signature = "1.5.0"
socks = "0.3.4"
tor-llcrypto = { version = "0.2.0", features = ["relay"] }
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
serial_test = "0.9.0"
which = "4.3.0"

[features]
offline-test = []
