# see https://github.com/eqrion/cbindgen/blob/master/docs.md

tab_width = 4
language = "C"
no_includes = true
usize_is_size_t = true
documentation = true
documentation_style = "c99"
line_length = 80
only_target_dependencies = true

[parse]
parse_deps = true
include = ["tor-interface"]
extra_bindings = ["tor-interface"]

[defines]
"target_os = windows" = "GOSLING_PLATFORM_WINDOWS"
"target_os = linux" = "GOSLING_PLATFORM_LINUX"
"target_os = macos" = "GOSLING_PLATFORM_MACOS"
"feature = mock-tor-provider" = "GOSLING_HAVE_MOCK_TOR_PROVIDER"
"feature = legacy-tor-provider" = "GOSLING_HAVE_LEGACY_TOR_PROVIDER"

[fn]
args = "horizontal"

[enum]
rename_variants = "SnakeCase"
enum_class = true
prefix_with_name = true

[export.rename]
"RawSocket" = "SOCKET"
"RawFd" = "int"

# typedefs
GoslingHandshakeHandle = "gosling_handshake_handle_t"
GoslingTcpSocket = "gosling_tcp_socket_t"
GoslingCircuitToken = "gosling_circuit_token_t"

# structs

GoslingLibrary = "gosling_library"
GoslingError = "gosling_error"
GoslingContext = "gosling_context"
GoslingEd25519PrivateKey = "gosling_ed25519_private_key"
GoslingV3OnionServiceId = "gosling_v3_onion_service_id"
GoslingX25519PrivateKey = "gosling_x25519_private_key"
GoslingX25519PublicKey = "gosling_x25519_public_key"
GoslingTorProvider = "gosling_tor_provider"
GoslingTargetAddress = "gosling_target_address"

# callbacks

GoslingEndpointClientHandshakeCompletedCallback = "gosling_endpoint_client_handshake_completed_callback_t"
GoslingEndpointClientHandshakeFailedCallback = "gosling_endpoint_client_handshake_failed_callback_t"
GoslingEndpointServerChannelSupportedCallback = "gosling_endpoint_server_channel_supported_callback_t"
GoslingEndpointServerHandshakeCompletedCallback = "gosling_endpoint_server_handshake_completed_callback_t"
GoslingEndpointServerHandshakeFailedCallback = "gosling_endpoint_server_handshake_failed_callback_t"
GoslingEndpointServerHandshakeRejectedCallback = "gosling_endpoint_server_handshake_rejected_callback_t"
GoslingEndpointServerHandshakeStartedCallback = "gosling_endpoint_server_handshake_started_callback_t"
GoslingEndpointServerPublishedCallback = "gosling_endpoint_server_published_callback_t"
GoslingIdentityClientHandshakeBuildChallengeResponseCallback = "gosling_identity_client_handshake_build_challenge_response_callback_t"
GoslingIdentityClientHandshakeChallengeResponseSizeCallback = "gosling_identity_client_handshake_challenge_response_size_callback_t"
GoslingIdentityClientHandshakeCompletedCallback = "gosling_identity_client_handshake_completed_callback_t"
GoslingIdentityClientHandshakeFailedCallback = "gosling_identity_client_handshake_failed_callback_t"
GoslingIdentityServerEndpointSupportedCallback = "gosling_identity_server_endpoint_supported_callback_t"
GoslingIdentityServerHandshakeBuildChallengeCallback = "gosling_identity_server_handshake_build_challenge_callback_t"
GoslingIdentityServerHandshakeChallengeSizeCallback = "gosling_identity_server_handshake_challenge_size_callback_t"
GoslingIdentityServerHandshakeClientAllowedCallback = "gosling_identity_server_handshake_client_allowed_callback_t"
GoslingIdentityServerHandshakeCompletedCallback = "gosling_identity_server_handshake_completed_callback_t"
GoslingIdentityServerHandshakeFailedCallback = "gosling_identity_server_handshake_failed_callback_t"
GoslingIdentityServerHandshakeRejectedCallback = "gosling_identity_server_handshake_rejected_callback_t"
GoslingIdentityServerHandshakeStartedCallback = "gosling_identity_server_handshake_started_callback_t"
GoslingIdentityServerHandshakeVerifyChallengeResponseCallback = "gosling_identity_server_handshake_verify_challenge_response_callback_t"
GoslingIdentityServerPublishedCallback = "gosling_identity_server_published_callback_t"
GoslingTorBootstrapCompletedCallback = "gosling_tor_bootstrap_completed_callback_t"
GoslingTorBootstrapStatusReceivedCallback = "gosling_tor_bootstrap_status_received_callback_t"
GoslingTorLogReceivedCallback = "gosling_tor_log_received_callback_t"
