[package]
name = "build_java_bindings"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "build_java_bindings"
path = "./build_java_bindings.rs"

[dependencies]
handlebars = "4.5.0"
serde =  { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10"
heck = "0.4.1"
