[package]
name = "cgosling-proc-macros"
version = "0.0.0"
rust-version = "1.70"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version = "2.0", features = ["parsing"]}
