[package]
name = "build_c_shared_bindings"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "build_c_bindings"
path = "./build_c_bindings.rs"

[dependencies]
handlebars = "4.3"
serde_json = "1.0"
