[package]
name = "gosling"
build = "build.rs"
authors = ["Richard Pospesel <richard@blueprintforfreespeech.net>"]
version = "0.0.1"

[build-dependencies]
cbindgen = "0.20.0"

[dependencies]
lazy_static = "1.4.0"
rust-crypto = "^0.2"
data-encoding = "2.3.2"

[lib]
name = "gosling"
crate-type = ["staticlib"]

