name: build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
      - name: Build Debug
        run: |
          make debug
      - name: Archive Debug
        uses: actions/upload-artifact@v3
        with:
          name: linux-debug
          path: |
            out/debug/gosling/crates/gosling-ffi/debug/libgoslingffi.a
            out/debug/gosling/crates/gosling-ffi/include/libgosling.h
      - name: Build Release
        run: |
          make release
      - name: Archive Release
        uses: actions/upload-artifact@v3
        with:
          name: linux-release
          path: |
            out/release/gosling/crates/gosling-ffi/release/libgoslingffi.a
            out/release/gosling/crates/gosling-ffi/include/libgosling.h

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          update: true
          install: >-
            make
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-boost
      - name: Configure Rust
        run: |
          PATH=$(cygpath $USERPROFILE)/.cargo/bin:$PATH
          rustup default stable-x86_64-pc-windows-gnu
      - name: Build Debug
        run: |
          PATH=$(cygpath $USERPROFILE)/.cargo/bin:$PATH
          make debug
      - name: Archive Debug
        uses: actions/upload-artifact@v3
        with:
          name: windows-debug
          path: |
            out/debug/gosling/crates/gosling-ffi/debug/libgoslingffi.a
            out/debug/gosling/crates/gosling-ffi/include/libgosling.h
      - name: Build Release
        run: |
          echo $PATH
          PATH=$(cygpath $USERPROFILE)/.cargo/bin:$PATH
          make release
      - name: Archive Release
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: |
            out/release/gosling/crates/gosling-ffi/release/libgoslingffi.a
            out/release/gosling/crates/gosling-ffi/include/libgosling.h

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          brew install boost
      - name: Build Debug
        run: |
          make debug
      - name: Archive Debug
        uses: actions/upload-artifact@v3
        with:
          name: macos-debug
          path: |
            out/debug/gosling/crates/gosling-ffi/debug/libgoslingffi.a
            out/debug/gosling/crates/gosling-ffi/include/libgosling.h
      - name: Build Release
        run: |
          make release
      - name: Archive Release
        uses: actions/upload-artifact@v3
        with:
          name: macos-release
          path: |
            out/release/gosling/crates/gosling-ffi/release/libgoslingffi.a
            out/release/gosling/crates/gosling-ffi/include/libgosling.h
