name: build

on: [push, pull_request]

jobs:
  linux:
    strategy:
      matrix:
        include:
          - debian-arch: i386
            cflags: -m32
            cxxflags: -m32
            rust-target: i686-unknown-linux-gnu
            cmake-find-root-path: /usr/lib/i386-linux-gnu
            arch: i386
          - debian-arch: amd64
            rust-target: x86_64-unknown-linux-gnu
            cmake-find-root-path: /usr/lib/x86_64-linux-gnu
            arch: x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture ${{ matrix.debian-arch }}
          sudo apt-get update
          sudo apt install -y gcc-multilib g++-multilib
          sudo apt-get install -y libc6:${{ matrix.debian-arch }} libstdc++6:${{ matrix.debian-arch }} libboost-all-dev:${{ matrix.debian-arch }} libncurses-dev:${{ matrix.debian-arch }} default-jdk:${{ matrix.debian-arch }} dpkg-dev
      - name: Configure Rust
        run: |
          rustup target add ${{ matrix.rust-target }}
          rustup default stable-${{ matrix.rust-target }}
      - name: Build Debug
        run: |
          cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=dist/debug -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JAVA_BINDINGS=ON -DCMAKE_C_FLAGS="${{ matrix.cflags }}" -DCMAKE_CXX_FLAGS="${{ matrix.cxxflags }}" -DCMAKE_FIND_ROOT_PATH=${{ matrix.cmake-find-root-path }}
          cmake --build build
          cmake --install build
      - name: Archive Debug
        run: |
          cd dist
          tar -cf gosling-linux-gnu-${{ matrix.arch }}-debug.tar debug
      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: gosling-linux-gnu-${{ matrix.arch }}-debug.tar
          path: dist/gosling-linux-gnu-${{ matrix.arch }}-debug.tar
      - name: Build Release
        run: |
          cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=dist/release -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JAVA_BINDINGS=ON -DCMAKE_C_FLAGS="${{ matrix.cflags }}"
          cmake --build build
          cmake --install build
      - name: Archive Release
        run: |
          cd dist
          tar -cf gosling-linux-gnu-${{ matrix.arch }}-release.tar release
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: gosling-linux-gnu-${{ matrix.arch }}-release.tar
          path: dist/gosling-linux-gnu-${{ matrix.arch }}-release.tar

  windows-gnu:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install MSYS2 Dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          update: true
          install: >-
            make
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-rust
            mingw-w64-clang-x86_64-boost
            mingw-w64-clang-x86_64-ncurses
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build Debug
        run: |
          # manually add java bins to PATH >:[
          export PATH=$(cygpath -u ${JAVA_HOME})/bin:$PATH
          mkdir -p build/debug
          cd build/debug
          cmake ../.. -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../dist/debug -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JAVA_BINDINGS=ON -DBUILD_EXAMPLES=ON -DBUILD_MSYS2_PKGBUILD=ON
          make
          make install
      - name: Archive Debug
        run: |
          cd dist
          tar -cf gosling-windows-gnu-debug.tar debug
      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: gosling-windows-gnu-debug.tar
          path: dist/gosling-windows-gnu-debug.tar
      - name: Build Release
        run: |
          # manually add java bins to PATH >:[
          export PATH=$(cygpath -u ${JAVA_HOME})/bin:$PATH
          mkdir -p build/release
          cd build/release
          cmake ../.. -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../dist/release -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JAVA_BINDINGS=ON -DBUILD_EXAMPLES=ON -DBUILD_MSYS2_PKGBUILD=ON
          make
          make install
      - name: Archive Release
        run: |
          cd dist
          tar -cf gosling-windows-gnu-release.tar release
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: gosling-windows-gnu-release.tar
          path: dist/gosling-windows-gnu-release.tar

  windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
            boost_version: 1.78.0
            toolset: msvc
      - name: Build Debug
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=dist/debug -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JAVA_BINDINGS=ON
          cmake --build build --config Debug
          cmake --install build --config Debug
      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: gosling-windows-mscvc-debug
          path: dist/debug
      - name: Build Release
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=dist/release -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JAVA_BINDINGS=ON
          cmake --build build --config Release
          cmake --install build --config Release
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: gosling-windows-mscvc-release
          path: dist/release


  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          brew install boost ncurses
      - name: Build Debug
        run: |
          mkdir -p build/debug
          cd build/debug
          cmake ../.. -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../dist/debug -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JAVA_BINDINGS=ON -DBUILD_EXAMPLES=ON -DBUILD_HOMEBREW_FORMULA=ON
          make
          make install
      - name: Archive Debug
        run: |
          cd dist
          tar -cf gosling-macos-debug.tar debug
      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: gosling-macos-debug.tar
          path: dist/gosling-macos-debug.tar
      - name: Build Release
        run: |
          mkdir -p build/release
          cd build/release
          cmake ../.. -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../dist/release -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JAVA_BINDINGS=ON -DBUILD_EXAMPLES=ON -DBUILD_HOMEBREW_FORMULA=ON
          make
          make install
      - name: Archive Release
        run: |
          cd dist
          tar -cf gosling-macos-release.tar release
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: gosling-macos-release.tar
          path: dist/gosling-macos-release.tar
