name: build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev libncurses-dev default-jdk
      - name: Build Debug
        run: |
          make install-debug
      - name: Archive Debug
        uses: actions/upload-artifact@v3
        with:
          name: linux-debug
          path: |
            dist/debug
      - name: Build Release
        run: |
          make install-release
      - name: Archive Release
        uses: actions/upload-artifact@v3
        with:
          name: linux-release
          path: |
            dist/release

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install MSYS2 Dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          update: true
          install: >-
            make
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-rust
            mingw-w64-clang-x86_64-boost
            mingw-w64-clang-x86_64-ncurses
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build Debug
        run: |
          # manually add java bins to PATH >:[
          export PATH=$(cygpath -u ${JAVA_HOME})/bin:$PATH
          make install-debug
      - name: Archive Debug
        uses: actions/upload-artifact@v3
        with:
          name: windows-debug
          path: |
            dist/debug
      - name: Build Release
        run: |
          # manually add java bins to PATH >:[
          export PATH=$(cygpath -u ${JAVA_HOME})/bin:$PATH
          make install-release
      - name: Archive Release
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: |
            dist/release

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          brew install boost ncurses openjdk@17
      - name: Build Debug
        run: |
          make install-debug
      - name: Archive Debug
        uses: actions/upload-artifact@v3
        with:
          name: macos-debug
          path: |
            dist/debug
      - name: Build Release
        run: |
          make install-release
      - name: Archive Release
        uses: actions/upload-artifact@v3
        with:
          name: macos-release
          path: |
            dist/release
