name: fuzz

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        fuzz-test:
          - honk_rpc_cargo_fuzz_test
          - tor_interface_crypto_cargo_fuzz_test
          - gosling_identity_server_cargo_fuzz_test
          - gosling_identity_client_cargo_fuzz_test
          - gosling_endpoint_server_cargo_fuzz_test
          - gosling_endpoint_client_cargo_fuzz_test
          - cgosling_cargo_fuzz_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Intall rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Install fuzzer
        run: |
          cargo install cargo-fuzz
      - name: Init Project
        run: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_FUZZ_TESTS=On -DFUZZ_TEST_MAX_TOTAL_TIME=1200
      - name: Fuzz Test
        run: |
          cd build
          ctest -R ${{ matrix.fuzz-test }} --verbose
