name: fuzz

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Intall rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Install fuzzer
        run: |
          cargo install cargo-fuzz
      - name: Init Project
        run: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_FUZZ_TESTS=On -DFUZZ_TEST_MAX_TOTAL_TIME=1200
      - name: Fuzz HonkRPC
        run: |
          cd build
          ctest -R honk_rpc_cargo_fuzz_test --verbose
      - name: Fuzz Tor Crypto
        run: |
          cd build
          ctest -R tor_interface_crypto_cargo_fuzz_test --verbose
      - name: Fuzz Identity Server
        run: |
          cd build
          ctest -R gosling_identity_server_cargo_fuzz_test --verbose
      - name: Fuzz Identity Client
        run: |
          cd build
          ctest -R gosling_identity_client_cargo_fuzz_test --verbose
      - name: Fuzz Endpoint Server
        run: |
          cd build
          ctest -R gosling_endpoint_server_cargo_fuzz_test --verbose
      - name: Fuzz Endpoint Client
        run: |
          cd build
          ctest -R gosling_endpoint_client_cargo_fuzz_test --verbose
      - name: Fuzz C-Gosling
        run: |
          cd build
          ctest -R cgosling_cargo_fuzz_test --verbose
