name: pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gosling
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
          cargo install cargo-tarpaulin
          sudo apt-get install -y doxygen markdown ruby-mustache
      - name: Build Code Coverage
        run: |
          make coverage-offline-release
      - name: Move Outputs
        run: |
          make release
          make install-release
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/release/pages
